# Generated by Django 3.2.16 on 2023-12-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(default=None, max_length=7, null=True, verbose_name='Color'),
        ),
    ]
